### ISSUE TITLE
github-ci: prevent of use docker images on builds testing

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#101]
For the following workflows:
```
debug_coverage.yml
release_asan_clang11.yml
release_clang.yml
release_lto_clang11.yml
release_lto.yml
release.yml
```
remove use of docker container debian-stretch and debian-buster, and run all on native ubuntu-18.04

This change would have different results for us:

positive:
- remove extra container step in workflow, it will give the ability to bootstrap the host better than inside container
- ubuntu-18.04 is one of default Github Actions OS - our free hosts we'll be the same as local
- debian-stretch uses old git package v.2.10 which prevents us from use checkout action of v2.3.4 version which works more correct than v1 (this was the issue with setup coveralls action, when found that with v2.3.4 it works correct and fails with v1 )
- more clear setup in local .*mk makefiles

negative:
- more packages would need to be installed, but caching may help

**Comment by Totktonada** [comment]
Please, describe a goal of the issue. A kind of:

* Get rid of docker image support (simplify imfrastructure and periodical manual actions to remember).
* Simplify workflows files in X, Y, Z.

Or you motivation is different?

We'll need to install all necessary dependencies each time. How much it will slowdown our CI jobs? Can we [cache](https://github.com/tarantool/setup-tarantool/blob/69a66d37a35917992a8e39085dd799a116aec1a1/src/main.ts#L147-L179) those dependencies (see also https://github.com/tarantool/tarantool/issues/5883#issuecomment-798778321).

NB: Don't forget to clean up `.travis.mk` and `.gitlab.mk` files after the change.

**Comment by avtikhon** [comment]
> Please, describe a goal of the issue. A kind of:
> 
> * Get rid of docker image support (simplify imfrastructure and periodical manual actions to remember).
> * Simplify workflows files in X, Y, Z.
> 
> Or you motivation is different?
> 
> We'll need to install all necessary dependencies each time. How much it will slowdown our CI jobs? Can we [cache](https://github.com/tarantool/setup-tarantool/blob/69a66d37a35917992a8e39085dd799a116aec1a1/src/main.ts#L147-L179) those dependencies (see also [tarantool/tarantool#5883 (comment)](https://github.com/tarantool/tarantool/issues/5883#issuecomment-798778321)).
> 
> NB: Don't forget to clean up `.travis.mk` and `.gitlab.mk` files after the change.

There are a lot of minor issues that can be resolved within this change, but also it would cost some other issues for us, so I agree that we need to investigate this suggestion and discuss before implementation.
