### ISSUE TITLE
github-ci: implement sources repository cleanup

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#102]
On MCS hosts sources repositories need cleanup from the previous run, check below:

Failed run:
https://github.com/avtikhon/tarantool/actions/runs/679090863/workflow
https://github.com/avtikhon/tarantool/runs/2174476438?check_suite_focus=true

After previous successful:
https://github.com/avtikhon/tarantool/actions/runs/678561594/workflow
https://github.com/avtikhon/tarantool/runs/2172664919?check_suite_focus=true

**Comment by Totktonada** [comment]
Can you list what exactly we should clean up? Old clones, build artifacts, testing artifacts. Something else?

Installed packages? I hope it is not very critical. `apt-get -y install <foo>` returns zero exit code, when `<foo>` is already installed.

Anyway, it seems quite logical to perform each run in an unique temporary directory. We can collect such directories periodically using cron. Will it does the work? Can GitHub Actions runner assign a new temporary working directory for a job each time transparently for the job?

The reason why I like this solution: this way we don't place any (tricky) clean up steps into our CI jobs. So the jobs are kept simple. The side reason is my feeling of cleanup actions of this kind: normally it should not be part of a job yaml file. Everything should be quite same as for GitHub public runners from a job yaml file perspective: just like we always run on a new machine.

**Comment by avtikhon** [comment]
> Can you list what exactly we should clean up? Old clones, build artifacts, testing artifacts. Something else?
> 

I've added in the top message of the current issue an example of such issue. It is seen there that using container part inside github workflow does not prevent from workspace removement, seems that it shared the workspace out of the container.

> Installed packages? I hope it is not very critical. `apt-get -y install <foo>` returns zero exit code, when `<foo>` is already installed.
> 

No, it's ok.

> Anyway, it seems quite logical to perform each run in an unique temporary directory. We can collect such directories periodically using cron. Will it does the work? Can GitHub Actions runner assign a new temporary working directory for a job each time transparently for the job?
> 
> The reason why I like this solution: this way we don't place any (tricky) clean up steps into our CI jobs. So the jobs are kept simple. The side reason is my feeling of cleanup actions of this kind: normally it should not be part of a job yaml file. Everything should be quite same as for GitHub public runners from a job yaml file perspective: just like we always run on a new machine.

Right, solution is correct, but it will cost for us to long run time. We always used fetching of the workspace instead of its cloning. And this way we decided to use even with special cleanup parts. Why do we want to change it for now ?
