### ISSUE TITLE
vinyl/gh.test.lua does not check whether fibers are finished

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-qa#106]
The test case was added in https://github.com/tarantool/tarantool/commit/e576ca91c9555a3eb1012a05fd873f56565f028d

And became broken in https://github.com/tarantool/tarantool/commit/42c64d06d5d1a3ec937b3c596af083a672a68ad8:

```diff
-while finished ~= 2 do fiber.sleep(0.01) end
+test_run:wait_cond(function() return finished ~= 2 end)
```

The condition was not reverted.

**Comment by Totktonada** [comment]
I looked at the test, because I found the following line in logs:

> 2021-03-26 17:35:21.482 [23345] main/132/lua utils.c:1014 E> LuajitError: [string "_ = fiber.create(function()     while cont do..."]:1: variable 'cont' is not declared

Despite the error the test passes.

(But I don't know why this situation occurs. The variable is declared before reading.)

I'm on Linux, tarantool is built in Debug mode.

**Comment by avtikhon** [comment]
> I looked at the test, because I found the following line in logs:
> 
> > 2021-03-26 17:35:21.482 [23345] main/132/lua utils.c:1014 E> LuajitError: [string "_ = fiber.create(function()     while cont do..."]:1: variable 'cont' is not declared
> 
> Despite the error the test passes.
> 
> (But I don't know why this situation occurs. The variable is declared before reading.)
> 
> I'm on Linux, tarantool is built in Debug mode.

Moved to separate issue to be able to close this one.

**Comment by Totktonada** [comment]
The main issue was fixed in https://github.com/tarantool/tarantool/pull/6168.
