### ISSUE TITLE
github-ci: setup self-host runners for workflows as additional resources

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#108]
Best solution for us have our self-runners hosts added to Github Actions hosts as additional resources.

Tried the following:

1. successfully run on Github Actions hosts with:
`runs-on: ubuntu-20.04`

2. successfully run on self-hosted runners with:
`runs-on: mcs_2_8_gh_clone`

3. failed to merge labels from above:
`runs-on: [mcs_2_8_gh_clone, ubuntu-20.04]`

Failed workflow [1] message:
No runner matching the specified labels was found: mcs_2_8_gh_clone, ubuntu-20.04

Investigating documents found that these labels works in other way [2]:
`These labels operate cumulatively, so a self-hosted runner’s labels must match all four to be eligible to process the job.`

For us it means that we must use the same labels as Github Actions native hosts have - we'll use 'ubuntu-20.04' label.

[1]: https://github.com/avtikhon/tarantool/actions/runs/704966289
[2]: https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow?WT.mc_id=docs-blog-jessde#using-custom-labels-to-route-jobs

**Comment by Totktonada** [comment]
Why don't add `ubuntu-20.04` label to the self-hosted runner?

**Comment by avtikhon** [comment]
> Why don't add `ubuntu-20.04` label to the self-hosted runner?

Right, seems it works.
