### ISSUE TITLE
Telegram notification is not sent (Linux)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-qa#112]
'release_clang' job:

> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
> AttributeError: module 'urllib' has no attribute 'quote_plus'

https://github.com/tarantool/tarantool/runs/2280702426

I suspect it may be related to [transition](https://github.com/tarantool/tarantool/issues/5652) from Python 2 to Python 3.

**Comment by avtikhon** [comment]
Right, in Python 3 quote_plus included into urllib.parse [1]:
```
Note The urllib module has been split into parts and renamed in Python 3 to urllib.request, urllib.parse, and urllib.error.
```
check the same issue [2].

[1]: https://docs.python.org/2/library/urllib.html
[2]: https://github.com/web2py/web2py/issues/1822
