### ISSUE TITLE
github-ci: Introduce pipeline for MacOS ARM64

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool-qa#120]
In scope of tarantool/tarantool#6068 we are fighting to enable ARM64 support: from several issues with build found within tarantool/tarantool#5983 to failures faced while running tests. This is the moment when we need to introduce regular routines (both Debug and RelWithDebInfo) for MacOS ARM64 platfroms to our CI .

**Comment by avtikhon** [comment]
On test hosts was made manual cleanup/update:
 - removed Python 3.9.5 (default on python3 brew installation).
 - blocked Python 3.9.5 installation by root file.
 - installed Rosetta with `softwareupdate --install-rosetta` to be able to run `arch -x86_64 <command>`  to be able to install and run Github Actions runner.
