### ISSUE TITLE
github-ci: Introduce pipeline for GNU/Linux ARM64

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool-qa#121]
In scope of tarantool/tarantool#5629 we are backporting patches from [vanilla LuaJIT](https://github.com/LuaJIT/LuaJIT) to enable ARM64 support on GNU/Linux. To make sure these patches definitely solve ARM64-related issue and break nothing, we need regular routines (both Debug and RelWithDebInfo) for GNU/Linux ARM64 platforms to our CI.

**Comment by avtikhon** [comment]
To setup the host for Github Actions and manual testings done:
1. added tarantool:tarantool user:group :
```adduser tarantool```
2. added other needed users to tarantool group:
```vi /etc/group```
3. added sudo to tarantool group:
```
chmod u+w /etc/sudoers
vi /etc/sudoers
chmod u-w /etc/sudoers
```
4. installed git for checkout ability:
``` apt update -y && apt install git```
5: installed Github Actions runner:
```
mkdir actions-runner && cd actions-runner# Download the latest runner package
curl -o actions-runner-linux-arm64-2.278.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.278.0/actions-runner-linux-arm64-2.278.0.tar.gz# Extract the installer
tar xzf ./actions-runner-linux-arm64-2.278.0.tar.gz
./config.sh --url https://github.com/avtikhon/tarantool --token <TOKEN>
nohup ./run.sh >run.log 2>&1 &
```
