### ISSUE TITLE
test: on 1.10 flaky fails vinyl/errinj.test.lua test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#134]
Tarantool 1.10.10-34-g97a7871c7
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: x86_64

Issue:
```
[001] vinyl/errinj.test.lua                                           [ fail ]
[001] 
[001] Test failed! Result content mismatch:
[001] --- vinyl/errinj.result	Fri Jul  2 14:26:42 2021
[001] +++ var/rejects/vinyl/errinj.reject	Fri Jul  2 14:32:43 2021
[001] @@ -851,7 +851,8 @@
[001]  ...
[001]  ret
[001]  ---
[001] -- - [3, 3]
[001] +- - [2, 2]
[001] +  - [3, 3]
[001]  ...
[001]  s:drop()
[001]  ---
[001] 
```

Reproduce commands:
```
cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=ON
make -j
cd test
./test-run.py vinyl/errinj.test.lua 
```

Artifacts:
[artifacts.zip](https://github.com/tarantool/tarantool/files/6755280/artifacts.zip)

**Comment by locker** [comment]
Fixed by https://github.com/tarantool/tarantool/commit/7c3a705f98eb805bf12a1983abe00c1f4406fdfc
