### ISSUE TITLE
Implement monitoring of CI/CD runners

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool-qa#139]
It probably will be useful to be able to see monitor our CI/CD runners by runner kind.

E.g. I'd like to see the following charts in Grafana:
- Linux runners load
- OSX runners load
- FreeBSD runners load
- M1 runners load
- etc.

If it is hard to do calculate precisely, maybe simple show the relative number of busy runners?

**Comment by Totktonada** [comment]
I briefly googled around.

Where runner logs are placed: https://docs.github.com/en/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners

The discussion about self-hosted runner monitoring: https://github.community/t/monitoring-self-hosted-runners-jobs-by-runner-id/146233

The discussion suggests to look at https://github.com/infinityworks/github-exporter (I see some usage examples [here](https://neillwturner.medium.com/github-actions-self-hosted-runners-on-kubernetes-2cc0da04d41a)). The linked GitHub Enterprise documentation suggests `collectd` — it is about hardware monitoring AFAIU.

**Comment by VitaliyaIoffe** [comment]
> Where runner logs are placed: https://docs.github.com/en/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners

If you jump to our self-hosted runners, you can find run.log

**Comment by NickVolynkin** [comment]
We're doing it with Zabbix.
