### ISSUE TITLE
Setup CI for Linux GC64

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool-qa#159]
Moving forward to enabling GC64 by default on Linux AMD64 need to setup CI and packages build.

Duplicate all Linux packages on AMD64 architecture with `--gc64` option, only on `master` branch (2.10 RC)

* Fedora
* CentOS
* Debian
* Ubuntu
* OpenSUSE is optional

Deploy extra runners to keep `full-ci` build time approximately the same.

**Comment by ylobankov** [comment]
Resolved by tarantool/tarantool#7065 and tarantool/tarantool#7082.
