### ISSUE TITLE
Make a reusable workflow for building and deploying packages

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#241]
Make a parameterized workflow with parameters: distributive, version, gc64/no, architecture.

Consequent steps:

1. Build a package
2. (Run tests) — will be implemented in the next issue as a separate job.
3. Deploy package with RWS to S3 — done on tags, maybe on nightly builds as well.

Make aggregate workflows for each distributive, call the reusable workflow with all required parameters.

**Comment by ylobankov** [comment]
Closed by https://github.com/tarantool/tarantool/pull/8970. It is implemented for tarantool since series-3.
