### ISSUE TITLE
Run tests on just-built packages in CI

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#243]
Continuation of #241.

Add the 2nd job "Testing" — install the package and run tests against the installed Tarantool.

The updated workflow looks like this:

Job 1: Building the package
Job 2: Running tests and deploying (when needed)

Use `needs` to chain jobs. Pass packages using the artifacts: https://github.com/actions/upload-artifact, https://github.com/actions/download-artifact.

We're using jobs and not steps here, because we want to be able to restart tests on the same package.

**Comment by ylobankov** [comment]
Closed by https://github.com/tarantool/tarantool/pull/8970. It is implemented for tarantool since series-3.
