### ISSUE TITLE
Update CI/CD with the latest Ubuntu and Fedora versions at the 1.10 branch

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#247]
Note: requirements are still in discussion. 

- [ ] Add Fedora 36
- [ ] Add Ubuntu 21.10 and 22.04
- [ ] Make a release 1.10.14 on the resulting set of distributions

**Comment by ylobankov** [comment]
Resolved by https://github.com/tarantool/tarantool/pull/7199
