### ISSUE TITLE
Build and publish packages for Alpine Linux

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#266]
- [x] Make a base build image and fix Alpine related issues in PackPack ~5sp
	- https://github.com/packpack/packpack-docker-images/pull/94
	- https://github.com/packpack/packpack/pull/146
	- https://github.com/packpack/packpack/pull/149
	- https://github.com/packpack/packpack/pull/150

- [x] Fix building Alpine packages and make CI workflows in Tarantool  ~5sp
	- https://github.com/tarantool/tarantool/pull/7942
	- ~~Enable testing while building Alpine packages~~
- [ ] ~~Make repositories, adjust tarantool/mkrepo and tarantool/rws when needed \~3sp~~
- [ ] ~~Update tarantool/installer.sh \~3sp, check scripted installation~~

This issue is a requirement for https://github.com/tarantool/docker/issues/187

---

The crossed-out items are not planned to be done anymore.

**Comment by foxzi** [comment]
I found problem with building packages under root. Fix it in https://github.com/packpack/packpack/pull/149.
