### ISSUE TITLE
Build and publish packages for Astra Linux

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#268]
1. Make a base build image in packpack/packpack ~5sp
2. Make CI pipelines in tarantool/tarantool ~5sp
3. Make repositories, adjust tarantool/mkrepo and tarantool/rws when needed ~3sp
4. Update tarantool/installer.sh ~3sp, check scripted installation

**Comment by ylobankov** [comment]
It is not planned to be done anymore.
