### ISSUE TITLE
Flaky test wal_off/alter.test.lua

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#273]
Test https://github.com/tarantool/tarantool/blob/master/test/wal_off/alter.test.lua is flaky:

gc: always gc64

![image](https://user-images.githubusercontent.com/8015154/195788396-80d2690f-43ae-4482-a305-52008452dee0.png)

![image](https://user-images.githubusercontent.com/8015154/195788517-7554fca5-0e5f-47f6-ae0e-1a3c26395743.png)

**Comment by Gumix** [comment]
According to the [Grafana dashboard](https://mon.tarantool.io/grafana/d/vQ35ub74k/test-statistics?orgId=1&var-bucket=multivac-tests&var-bucket_table=multivac-table&var-job_name=All&var-test_name=wal_off%2Falter.test.lua&var-branch=All&var-os_version=All&var-architecture=All&var-gc64=All&var-compiler_version=All&var-libc_version=All&var-debug=All&var-configuration=All&var-test_type=All&var-test_subtype=All&var-test_attempt=All&var-period=1w&var-tag=_start), there are no fails in the last 3 months.

**Comment by Gumix** [comment]
Reproduced by:
```bash
./test-run.py -j 100 $(yes wal_off/alter | head -100)
```
```yaml
---
- error: fiber slice is exceeded
...
```
This test disables WAL, that's why it doesn't yield.
