### ISSUE TITLE
test: flaky box-luatest/pagination_netbox_test.lua

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#288]
Test https://github.com/tarantool/tarantool/blob/master/test/box-luatest/pagination_netbox_test.lua is flaky:

OS: Linux only
branch: master
arch: aarch64 only

<img width="812" alt="Screenshot 2022-12-06 at 12 44 58" src="https://user-images.githubusercontent.com/8015154/205840551-e8e83204-be16-4d62-bbef-4aa7a4e7c6bd.png">

**Comment by Buristan** [comment]
Fixed via https://github.com/tarantool/tarantool/commit/15e62a67d3e8d60e85b7c7dc6bc80cd9bb23d79d (backported in 2.11 via https://github.com/tarantool/tarantool/commit/a7a02300721413230c7693e39e99a96927015401). JIT for the test is enabled back by the https://github.com/tarantool/tarantool/commit/915e0b3a4475b12ec49320421569524dc8488aed (backported in 2.11 via https://github.com/tarantool/tarantool/commit/dbbeaff982022288faafb773930c75ba938f62f2).
See also tarantool/tarantool#7739, #291.
