### ISSUE TITLE
A lot of hung test-run workers in CI

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-qa#96]
We see a lot of situations in CI that looks like hung workers. This looks as a problem in test-run or testing infrastructure, not even in tests.

I propose to start debugging from test-run: either run workers under strace or instrument them with `color_stdout()` prints and perform runs in CI to spot the case. Can we reach some resource limit (say, number of file descriptors) and spin trying to acquire it?

May it be relevant to the recent transition to Python 3?

Example: https://github.com/tarantool/tarantool/runs/2126385328

**Comment by Totktonada** [comment]
The list of fixed and known problems around hanging workers is below.

- [x] https://github.com/tarantool/test-run/pull/275
- [ ] https://github.com/tarantool/test-run/issues/276

**Comment by NickVolynkin** [comment]
@Totktonada this issue was supposedly resolved by https://github.com/tarantool/test-run/pull/302. There's also https://github.com/tarantool/test-run/issues/333 that we're currently working on. Can we close this particular issue (#96)?

**Comment by Totktonada** [comment]
Okay. Ideally it would be nice if you would just link to multivac results and show that everything is fine. However multivac does not catch 'worker hang' situations AFAIR (and the results are not updated now AFAIS).
