### ISSUE TITLE
resources: disk bound tests need to run in special way

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#97]
During investigation issue #24 found that there was the issue with not enough timeout to finish the test on host with too huge disk bound usage from this test. It produced the discussion how highly disk bound test should be run - this issue created to provide way for such tests. Main disk activities happens on tests with vinyl configuration either 'vinyl/' suite. To investigate this issue more deep investigation is needed:

- [ ] [need to implement 'vardisk' disk usage collection routine](https://github.com/tarantool/tarantool-qa/issues/97#issuecomment-801003064) (tarantool/test-run#308)
- [ ] need to create solution to run such tests

**Comment by Totktonada** [comment]
> 1. need to check all tests and find disk bound tests

I would want to collect statistics right from test-run or in some way that works in CI. So we'll see actual behaviour in CI.

**Comment by avtikhon** [comment]
Working on this issue and after creating pull request with solution found that the current statistic is really good and fine for HDD based hosts. But for SSD this statistics doesn't show anything countable except that any of SSD parallel RW channels were in use, but not all, while SSD may have it and 16 and 64 and use only some of it doesn't feed and overload its use. We use in Github Actions and in MCS only hosts with SSD which are really fast and such patch won't help us any kind. Decided to stop this work till it will be needed.
